name: example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: '>=3.4.0-34.1.pre'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  screen_recorder:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
